CREATE TABLE IF NOT EXISTS `#__ampz_stats` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`date_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
`network` VARCHAR(50)  NOT NULL ,
`position` VARCHAR(50)  NOT NULL ,
`url` VARCHAR(2000)  NOT NULL ,
`title` VARCHAR(2000)  NOT NULL ,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `#__ampz` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET utf8 NOT NULL,
  `params` text CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8 AUTO_INCREMENT=0;
